export const VERIFICATION_EMAIL_COOLDOWN_SECONDS = 60;
export const PASSWORD_RESET_EMAIL_COOLDOWN_SECONDS = 60;
export const AUTH_PASSWORD_MIN_LENGTH = 8;
export const AUTH_PASSWORD_MAX_LENGTH = 128;
